name: "CI/CD for CDK"

on:
  push:
    branches:
      - main
    paths:
      - "infra/**"
      - ".github/**/infra.ya?ml"
  pull_request:
  workflow_dispatch:

env:
  AWS_DEFAULT_REGION: "ap-northeast-1"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

defaults:
  run:
    working-directory: infra

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Setup dependencies
        run: npm ci

      - name: Bootstrap CDK
        run: npx cdk bootstrap

      # 不要？？
      - name: Build
        run: npm run build

      - name: Hello, World!
        run: echo Hello, World!

      # - name: Unit tests
      #   if: contains(github.event_name, 'pull_request')
      #   run: npm run test:app

      - name: CDK Diff Check
        # if: contains(github.event_name, 'pull_request')
        run: npx cdk diff

      # - name: Snapshot tests
      #   if: contains(github.event_name, 'pull_request')
      #   run: npm run test:snapshot -- -u

      # - name: CDK Deploy
      #   if: contains(github.event_name, 'push')
      #   run: npx cdk deploy
