name: "Lambda Build and Test"

on:
  push:
    branches:
      - main
    paths:
      - "lambda/**/*.mjs"
      - ".github/**/lambda.ya?ml"
  pull_request:
  workflow_dispatch:

defaults:
  run:
    working-directory: lambda

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Setup dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Hello World!
        run: echo Hello, World!

      - name: Test
        run: npm test
