name: "Lambda Build and Test"

on:
  push:
    branches:
      - develop
    paths:
      - "lambda/**/*.mjs"
      - ".github/**/lambda.ya?ml"
  pull_request:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    working-directory: lambda
    shell: bash

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: actionlint
        uses: actions/checkout@v4

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          # cache: npm
          # cache-dependency-path: ./lambda/package-lock.json

      # ここから要修正
      - name: Setup dependencies
        run: |
          echo "Current directory: $(pwd)"
          ls -la
          npm ci
        working-directory: lambda/lambda-layer/nodejs

      - name: Build
        run: npm run build

      - name: Package Lambda Layer
        run: |
          cd lambda/lambda-layer
          zip -r layer.zip nodejs
        working-directory: lambda/lambda-layer

      # - name: Test
      #   run: npm test
